# This is just a proof of concept for how a proxy config could exist
version: "3.8"
services:
    onboarding:
        build:
            context: .
            args:
                SERVICE: onboarding
        environment:
            RELAYER_HOST: relayer_proxy
            RELAYER_PORT: 5050
        ports:
            - "3000:3000"
        networks:
            - "overlay"
            - "private"
    relayer_proxy:
        build:
            context: ./haproxy
        networks:
            - "private"
    relayer1:
        build:
            context: .
            args:
                SERVICE: relayer
        environment:
            ADDRESS: "0x1"
        networks:
            - "private"
    relayer2:
        build:
            context: .
            args:
                SERVICE: relayer
        environment:
            ADDRESS: "0x2"
        networks:
            - "private"

networks:
    overlay:
    private:
