export declare const prepareStartSession: (...args: any[]) => Promise<void>;
export declare const prepareDeployWallet: (...args: any[]) => Promise<void>;
export declare const preparePepperRequest: (...args: any[]) => Promise<void>;
export declare const recordPepperAndIdentifier: (...args: any[]) => Promise<void>;
export declare const prepareSetAccount: (...args: any[]) => Promise<void>;
export declare const resetRetryCounter: (context: any, events: any, done: any) => any;
export declare const waitForWallet: (...args: any[]) => Promise<void>;
export declare const prepareSubsidisedAttestations: (...args: any[]) => Promise<void>;
export declare const prepareSelectIssuers: (...args: any[]) => Promise<void>;
export declare function logHeaders(requestParams: any, response: any, context: any, ee: any, next: any): any;
export declare const waitForTransaction: (...args: any[]) => Promise<void>;
export declare function getWallet(contractKit: any, address: string): Promise<any>;
export declare function walletNotDeployed(context: any, next: any): any;
export declare function latestTxNotConfirmed(context: any, next: any): any;
export declare function saveStartSessionStatus(requestParams: any, response: any, context: any, ee: any, next: any): Promise<any>;
export declare function startSessionRateLimited(context: any, next: any): any;
export declare const countWalletTry: (_c: any, events: any, done: any) => any;
export declare const countSetAccountTry: (_c: any, events: any, done: any) => any;
export declare const countRequestAttestationTry: (_c: any, events: any, done: any) => any;
export declare const countSelectIssuersTry: (_c: any, events: any, done: any) => any;
