apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: komenci
  name: komenci
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: komenci
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
