name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Install dependencies
        run: |
          yarn
      - name: Install celo-monorepo dependencies
        run: |
            yarn --cwd ./libs/celo
      - name: Build celo-monorepo dependencies
        run : |
            yarn --cwd ./libs/celo/packages/base build
            yarn --cwd ./libs/celo/packages/utils build
            yarn --cwd ./libs/celo/packages/dev-utils build
            yarn --cwd ./libs/celo/packages/contractkit build:gen
            yarn --cwd ./libs/celo/packages/contractkit build
            yarn --cwd ./libs/celo/packages/phone-number-privacy-common build
      - name: Run linters
        run: |
            yarn lint
      - name: Run postgres for testing
        run: |
            docker run --name pg-docker -e POSTGRES_PASSWORD=docker -d -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data  postgres
      - name: Run unit tests
        run: |
            yarn test:cov
      - name: Run integration tests
        run: |
            yarn test:e2e