name: Build

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '10.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn cache
        uses: bowd/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache
        if: steps.restore-komenci.outputs.cache-hit != 'true'
      - name: Install Komenci dependencies
        run: yarn
      - name: Build KomenciKit dependencies
        run: yarn run build:komencikit
      - name: Run linters
        run: yarn lint
      - name: Setup testing config
        run: |
            cp apps/onboarding/.env.test.ci apps/onboarding/.env.test
            cp apps/onboarding/.env.test.ci apps/onboarding/.env
            cp apps/relayer/.env.test.ci apps/relayer/.env.test
            cp apps/relayer/.env.test.ci apps/relayer/.env
      - name: Run postgres for testing
        run: |
            docker run --name pg-docker -e POSTGRES_PASSWORD=docker -d -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data  postgres
      - name: Run unit tests
        run: |
            yarn test:cov
      - name: Run integration tests
        run: |
            yarn test:e2e
