name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - uses: actions/setup-node@v1
        with:
            node-version: '10.x'
      - name: Install dependencies
        run: |
          yarn
      - name: Run linters
        run: |
            yarn lint
      - name: Install celo-monorepo dependencies
        run: |
            yarn deps:celo:install
      - name: Build celo-monorepo dependencies
        run : |
            yarn deps:celo:build
      - name: Run postgres for testing
        run: |
            docker run --name pg-docker -e POSTGRES_PASSWORD=docker -d -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data  postgres
      - name: Run unit tests
        run: |
            yarn test:cov
      - name: Run integration tests
        run: |
            yarn test:e2e