name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: |
          npm i
      - name: Run linters
        run: npm run lint
      - name: Run postgres for testing
        run: |
          docker run --name pg-docker -e POSTGRES_PASSWORD=docker -d -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data  postgres
      - name: Run unit tests
        run:  npm run test:cov --forceExit --detectOpenHandles
      - name: Run integration tests
        run: |
          npm run test:e2e --forceExit --detectOpenHandles