name: Deploy to AKS Cluster
on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: Azure/docker-login@v1
      with:
        login-server: celotestnet.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        (while true; do
          df -h
          sleep 15
        done) &

        docker pull celotestnet.azurecr.io/komenci/komenci:latest

        docker build \
            -t celotestnet.azurecr.io/komenci/komenci:${{ github.sha }} \
            -t celotestnet.azurecr.io/komenci/komenci:latest \
            --cache-from celotestnet.azurecr.io/komenci/komenci:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .

        docker push celotestnet.azurecr.io/komenci/komenci:${{ github.sha }}
        docker push celotestnet.azurecr.io/komenci/komenci:latest

