name: Deploy to AKS Cluster
on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: Azure/docker-login@v1
      with:
        login-server: celotestnet.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        export SERVICE=onboarding
        docker build . -t celotestnet.azurecr.io/komenci/onboarding:${{ github.sha }}
        docker push celotestnet.azurecr.io/komenci/onboarding:${{ github.sha }}
        export SERVICE=relayer
        docker build . -t celotestnet.azurecr.io/komenci/relayer:${{ github.sha }}
        docker push celotestnet.azurecr.io/komenci/relayer:${{ github.sha }}
