name: Run Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '10.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn cache
        uses: bowd/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache
        if: steps.restore-komenci.outputs.cache-hit != 'true'
      - name: Install Komenci dependencies
        run: yarn
      - name: Run linters
        run: yarn lint
      - name: Setup testing config
        run: |
            cp packages/apps/api.env.test.ci packages/apps/api/.env.test
            cp packages/apps/api/.env.test.ci packages/apps/api/.env
            cp packages/apps/relayer/.env.test.ci packages/apps/relayer/.env.test
            cp packages/apps/relayer/.env.test.ci packages/apps/relayer/.env
      - name: Run komencikit tests
        run: yarn --cwd libs/komencikit test
      - name: Run unit tests
        run: yarn test:cov
      - name: Run postgres for e2e tests
        run: |
            docker run --name pg-docker \
              -e POSTGRES_PASSWORD=docker \
              -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data \
              -d -p 5432:5432 postgres
      - name: Run integration tests
        run: yarn test:e2e
